//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukGelisimi_MVC.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cocuk_Gelisimi_DbEntities1 : DbContext
    {
        public Cocuk_Gelisimi_DbEntities1()
            : base("name=Cocuk_Gelisimi_DbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table_About> Table_About { get; set; }
        public virtual DbSet<Table_Activity> Table_Activity { get; set; }
        public virtual DbSet<Table_Cognitive_Enhancement> Table_Cognitive_Enhancement { get; set; }
        public virtual DbSet<Table_CognitiveContent> Table_CognitiveContent { get; set; }
        public virtual DbSet<Table_G_Information> Table_G_Information { get; set; }
        public virtual DbSet<Table_General_Evaluation> Table_General_Evaluation { get; set; }
        public virtual DbSet<Table_Language_Development> Table_Language_Development { get; set; }
        public virtual DbSet<Table_LanguageContent> Table_LanguageContent { get; set; }
        public virtual DbSet<Table_Motor_Development> Table_Motor_Development { get; set; }
        public virtual DbSet<Table_MotorContent> Table_MotorContent { get; set; }
        public virtual DbSet<Table_Picture> Table_Picture { get; set; }
        public virtual DbSet<Table_SelfCareAbility> Table_SelfCareAbility { get; set; }
        public virtual DbSet<Table_SelfCareAbilityContent> Table_SelfCareAbilityContent { get; set; }
        public virtual DbSet<Table_SocialEmitionalContent> Table_SocialEmitionalContent { get; set; }
        public virtual DbSet<Table_SocialEmotionalDevelopment> Table_SocialEmotionalDevelopment { get; set; }
        public virtual DbSet<Table_Student> Table_Student { get; set; }
    }
}
