//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukGelisimi_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Picture
    {
        public short PictureID { get; set; }
        public string Picture { get; set; }
        public Nullable<short> ActivityID { get; set; }
        public Nullable<short> SliderOrder { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
