//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukGelisimi_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_SelfCareAbilityContent
    {
        public byte SelfCareAbilityContentID { get; set; }
        public string SelfCareAbilityGain1 { get; set; }
        public string SelfCareAbilityGain2 { get; set; }
        public string SelfCareAbilityGain3 { get; set; }
        public string SelfCareAbilityGain4 { get; set; }
        public string SelfCareAbilityGain5 { get; set; }
        public string SelfCareAbilityGain6 { get; set; }
        public string SelfCareAbilityGain7 { get; set; }
        public string SelfCareAbilityGain8 { get; set; }
    }
}
