//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukGelisimi_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_MotorContent
    {
        public byte MotorContentID { get; set; }
        public string MotorGain1 { get; set; }
        public string MotorGain2 { get; set; }
        public string MotorGain3 { get; set; }
        public string MotorGain4 { get; set; }
        public string MotorGain5 { get; set; }
    }
}
