//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukGelisimi_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Student()
        {
            this.Table_Cognitive_Enhancement = new HashSet<Table_Cognitive_Enhancement>();
            this.Table_G_Information = new HashSet<Table_G_Information>();
            this.Table_General_Evaluation = new HashSet<Table_General_Evaluation>();
            this.Table_Language_Development = new HashSet<Table_Language_Development>();
            this.Table_Motor_Development = new HashSet<Table_Motor_Development>();
            this.Table_SelfCareAbility = new HashSet<Table_SelfCareAbility>();
            this.Table_SocialEmotionalDevelopment = new HashSet<Table_SocialEmotionalDevelopment>();
        }
    
        public short StudentID { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentLastName { get; set; }
        public string StudentYearAsMonth { get; set; }
        public string StudentPicture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Cognitive_Enhancement> Table_Cognitive_Enhancement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_G_Information> Table_G_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_General_Evaluation> Table_General_Evaluation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Language_Development> Table_Language_Development { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Motor_Development> Table_Motor_Development { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_SelfCareAbility> Table_SelfCareAbility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_SocialEmotionalDevelopment> Table_SocialEmotionalDevelopment { get; set; }
    }
}
