//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukGelisimi_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_CognitiveContent
    {
        public byte CognitiveContentID { get; set; }
        public string CognitiveGain1 { get; set; }
        public string CognitiveGain2 { get; set; }
        public string CognitiveGain3 { get; set; }
        public string CognitiveGain4 { get; set; }
        public string CognitiveGain5 { get; set; }
        public string CognitiveGain6 { get; set; }
        public string CognitiveGain7 { get; set; }
        public string CognitiveGain8 { get; set; }
        public string CognitiveGain9 { get; set; }
        public string CognitiveGain10 { get; set; }
        public string CognitiveGain11 { get; set; }
        public string CognitiveGain12 { get; set; }
        public string CognitiveGain13 { get; set; }
        public string CognitiveGain14 { get; set; }
        public string CognitiveGain15 { get; set; }
        public string CognitiveGain16 { get; set; }
        public string CognitiveGain17 { get; set; }
        public string CognitiveGain18 { get; set; }
        public string CognitiveGain19 { get; set; }
        public string CognitiveGain20 { get; set; }
        public string CognitiveGain21 { get; set; }
    }
}
