//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukGelisimi_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_SocialEmitionalContent
    {
        public byte SocialEmotionalContentID { get; set; }
        public string SocialEmotionalContent1 { get; set; }
        public string SocialEmotionalContent2 { get; set; }
        public string SocialEmotionalContent3 { get; set; }
        public string SocialEmotionalContent4 { get; set; }
        public string SocialEmotionalContent5 { get; set; }
        public string SocialEmotionalContent6 { get; set; }
        public string SocialEmotionalContent7 { get; set; }
        public string SocialEmotionalContent8 { get; set; }
        public string SocialEmotionalContent9 { get; set; }
        public string SocialEmotionalContent10 { get; set; }
        public string SocialEmotionalContent11 { get; set; }
        public string SocialEmotionalContent12 { get; set; }
        public string SocialEmotionalContent13 { get; set; }
        public string SocialEmotionalContent14 { get; set; }
        public string SocialEmotionalContent15 { get; set; }
        public string SocialEmotionalContent16 { get; set; }
        public string SocialEmotionalContent17 { get; set; }
    }
}
