//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukGelisimi_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_LanguageContent
    {
        public byte LanguageContentID { get; set; }
        public string LanguageGain1 { get; set; }
        public string LanguageGain2 { get; set; }
        public string LanguageGain3 { get; set; }
        public string LanguageGain4 { get; set; }
        public string LanguageGain5 { get; set; }
        public string LanguageGain6 { get; set; }
        public string LanguageGain7 { get; set; }
        public string LanguageGain8 { get; set; }
        public string LanguageGain9 { get; set; }
        public string LanguageGain10 { get; set; }
        public string LanguageGain11 { get; set; }
        public string LanguageGain12 { get; set; }
    }
}
