//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukGelisimi_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_About
    {
        public short AboutMeID { get; set; }
        public string MyName { get; set; }
        public string MySurname { get; set; }
        public string MyPhoneNumber { get; set; }
        public string MyEmail { get; set; }
        public string MyTwitterLink { get; set; }
        public string MyInstagramLink { get; set; }
        public string MyFacebookLink { get; set; }
        public string MyYoutubeLink { get; set; }
        public string MyLinkedInLink { get; set; }
        public string MyAddress { get; set; }
        public string AboutMe { get; set; }
        public string MyPicture { get; set; }
    }
}
